"""drop_agent_credentials

Revision ID: a1859d63e07b
Revises: 0019
Create Date: 2026-06-09 01:47:51.919320
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1859d63e07b'
down_revision: str | None = '0019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_mcp_bindings_installation', table_name='agent_mcp_bindings')
    op.create_index(op.f('ix_agent_mcp_bindings_installation_id'), 'agent_mcp_bindings', ['installation_id'], unique=False)
    op.drop_index('ix_agents_name_active', table_name='agents', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.drop_column('agents', 'api_key_encrypted')
    op.drop_column('agents', 'base_url')
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'provider')
    op.drop_index('idx_mcp_servers_args_hash', table_name='mcp_servers')
    op.drop_index('idx_mcp_servers_name', table_name='mcp_servers')
    op.drop_index('idx_mcp_servers_slug', table_name='mcp_servers')
    op.drop_index('idx_mcp_servers_status', table_name='mcp_servers')
    op.drop_constraint('uq_mcp_servers_name', 'mcp_servers', type_='unique')
    op.drop_constraint('uq_mcp_servers_slug', 'mcp_servers', type_='unique')
    op.create_index(op.f('ix_mcp_servers_args_hash'), 'mcp_servers', ['args_hash'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=True)
    op.create_index(op.f('ix_mcp_servers_slug'), 'mcp_servers', ['slug'], unique=True)
    op.create_index(op.f('ix_mcp_servers_status'), 'mcp_servers', ['status'], unique=False)
    op.drop_index('idx_mcp_tool_call_logs_created', table_name='mcp_tool_call_logs')
    op.create_index(op.f('ix_mcp_tool_call_logs_created_at'), 'mcp_tool_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_templates_is_deleted'), 'templates', ['is_deleted'], unique=False)
    op.drop_index('idx_workspace_mcp_installations_mcp', table_name='workspace_mcp_installations')
    op.create_index(op.f('ix_workspace_mcp_installations_mcp_id'), 'workspace_mcp_installations', ['mcp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_mcp_installations_mcp_id'), table_name='workspace_mcp_installations')
    op.create_index('idx_workspace_mcp_installations_mcp', 'workspace_mcp_installations', ['mcp_id'], unique=False)
    op.drop_index(op.f('ix_templates_is_deleted'), table_name='templates')
    op.drop_index(op.f('ix_mcp_tool_call_logs_created_at'), table_name='mcp_tool_call_logs')
    op.create_index('idx_mcp_tool_call_logs_created', 'mcp_tool_call_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_mcp_servers_status'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_slug'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_args_hash'), table_name='mcp_servers')
    op.create_unique_constraint('uq_mcp_servers_slug', 'mcp_servers', ['slug'])
    op.create_unique_constraint('uq_mcp_servers_name', 'mcp_servers', ['name'])
    op.create_index('idx_mcp_servers_status', 'mcp_servers', ['status'], unique=False)
    op.create_index('idx_mcp_servers_slug', 'mcp_servers', ['slug'], unique=False)
    op.create_index('idx_mcp_servers_name', 'mcp_servers', ['name'], unique=False)
    op.create_index('idx_mcp_servers_args_hash', 'mcp_servers', ['args_hash'], unique=False)
    op.add_column('agents', sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('base_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_index('ix_agents_name_active', 'agents', ['name'], unique=True, postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_agent_mcp_bindings_installation_id'), table_name='agent_mcp_bindings')
    op.create_index('idx_agent_mcp_bindings_installation', 'agent_mcp_bindings', ['installation_id'], unique=False)
    # ### end Alembic commands ###
